# Docker Compose file for multi-container setup
version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_ACCESS_KEY=${ADMIN_ACCESS_KEY}
  # bot:
  #   build: ./bot
  #   environment:
  #     DISCORD_TOKEN: ${DISCORD_TOKEN}
  #     OPENAI_API_KEY: ${OPENAI_API_KEY}
  #     API_URL: ${API_URL}
  #     TARGET_CHANNEL: ${TARGET_CHANNEL}
  #     WEB_UI_URL: ${WEB_UI_URL}
  #   depends_on:
  #     - web
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: betapp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: betdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
